---
- hosts: server6.abc.com
  user: root
  sudo: yes
  tasks:
    - name: stop tomcat
      command: nohup /usr/local/tomcat/apache-tomcat-7.0.78/bin/catalina.sh stop
    - name: copy war file
      copy: src=/opt/test/WebProject.war dest=/usr/local/tomcat/apache-tomcat-7.0.78/webapps/
    - name: start tomcat
      command: nohup /usr/local/tomcat/apache-tomcat-7.0.78/bin/catalina.sh start
