---
- hosts: webserver
  user: test
  sudo: yes
  tasks:
   - name: installing packages
     yum: name={{item}} state=installed
     with_items:
           - curl
           - telnet
           - lynx
