---
- hosts: webserver
  user: test
  sudo: yes
  tasks: 
    - name: installing httpd package
      yum: name=httpd state=installed
      tags:
           - install
    - name: copying index file
      copy: src=index.html dest=/var/www/html/index.html
      tags:
           - copy
    - name: restarting httpd server
      service: name=httpd state=started
      tags:
           - start
