---
- hosts: webserver
  user: test
  sudo: yes
  gather_facts: yes
  tasks: 
    - name: installing httpd package
      yum: name=httpd state=installed
      when: ansible_os_family=="RedHat"
    - name: installing apache package
      apt: name=apache2 state=installed
      when: ansible_os_family=="Debian"
    - name: copying index file
      copy: src=index.html dest=/var/www/html/index.html
    - name: restarting httpd server
      service: name=httpd state=started
